# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ergativegpt',
                'doc_host': 'https://wuqui.github.io',
                'git_url': 'https://github.com/wuqui/ergativegpt',
                'lib_path': 'ergativegpt'},
  'syms': { 'ergativegpt.core': {'ergativegpt.core.UtteranceClassification': ('core.html#utteranceclassification', 'ergativegpt/core.py')},
            'ergativegpt.src': { 'ergativegpt.src.UtteranceClassification': ('src.html#utteranceclassification', 'ergativegpt/src.py'),
                                 'ergativegpt.src.get_metrics': ('src.html#get_metrics', 'ergativegpt/src.py')}}}
