# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ergativegpt',
                'doc_host': 'https://wuqui.github.io',
                'git_url': 'https://github.com/wuqui/ergativegpt',
                'lib_path': 'ergativegpt'},
  'syms': {'ergativegpt.core': {'ergativegpt.core.foo': ('core.html#foo', 'ergativegpt/core.py')}}}
