# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ergativegpt',
                'doc_host': 'https://wuqui.github.io',
                'git_url': 'https://github.com/wuqui/ergativegpt',
                'lib_path': 'ergativegpt'},
  'syms': { 'ergativegpt.config': { 'ergativegpt.config.ExperimentConfig': ('config.html#experimentconfig', 'ergativegpt/config.py'),
                                    'ergativegpt.config.load_config': ('config.html#load_config', 'ergativegpt/config.py')},
            'ergativegpt.core': {'ergativegpt.core.UtteranceClassification': ('core.html#utteranceclassification', 'ergativegpt/core.py')},
            'ergativegpt.data': { 'ergativegpt.data.load_experiment_data': ('data.html#load_experiment_data', 'ergativegpt/data.py'),
                                  'ergativegpt.data.read_linguistic_data': ('data.html#read_linguistic_data', 'ergativegpt/data.py')},
            'ergativegpt.src': { 'ergativegpt.src.UtteranceClassification': ('src.html#utteranceclassification', 'ergativegpt/src.py'),
                                 'ergativegpt.src.get_metrics': ('src.html#get_metrics', 'ergativegpt/src.py')}}}
