# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_src.ipynb.

# %% auto 0
__all__ = ['UtteranceClassification']

# %% ../nbs/01_src.ipynb 3
from langchain.pydantic_v1 import BaseModel, Field

class UtteranceClassification(BaseModel):
    """Classifying the utterances according to linguistic criteria."""
    gpt_transitivity: int = Field(..., description="Whether this sentence is transitive (label: 1) or intransitive (label: 0)")
    gpt_subject: str = Field(..., description='The subject in this sentence that you considered for your classification.')
    gpt_verb: str = Field(..., description='The verb in this sentence that you considere for your classification.')
    gpt_object: str = Field(..., description='The object in this sentence that you considered for your classification.')
    gpt_subject_animacy: str = Field(..., description='Whether the subject in this sentence that you considered for your classification is animate (label: Animate) or Inanimate (label: Animate).')
    gpt_subject_role: str = Field(..., description='Whether the subject in this sentence that you considered for your classification has the semantic role of Agent (label: Agent) or Patient (label: Patient).')
